# Generated by Django 5.1 on 2024-08-24 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TileBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_blue_tiles', models.SmallIntegerField()),
                ('number_of_orange_tiles', models.SmallIntegerField()),
                ('number_of_red_tiles', models.SmallIntegerField()),
                ('number_of_black_tiles', models.SmallIntegerField()),
                ('number_of_white_tiles', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(max_length=200)),
                ('number_of_tiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_of_<django.db.models.fields.textfield>_tiles+', to='new_game.tilebag')),
            ],
        ),
    ]
